[[redirects]]
  from = "/builds"
  to = "https://app.netlify.com/sites/priceless-liskov-5ad496/deploys"

[[redirects]]
  from="/story-graph"
  to="https://app.thestorygraph.com/profile/mjocc"

[[redirects]]
  from="/books"
  to="https://app.thestorygraph.com/profile/mjocc"

[[redirects]]
  from="/blog"
  to="https://blog.mjocc.dev"

[build]
  command = "yarn run build"
  publish = ".next"
